/**
 * Seeded exact-output parity: the vendored `planWeekAdvanced` must reproduce,
 * byte-for-byte, the plans produced by the CURRENT WEB planner.
 *
 * `__fixtures__/expected/vectors.json` was generated by running
 * `src/lib/mealPlanner.ts` (web) under `mulberry32(seed)` for each spec
 * (see `scratchpad/gen-vectors.mjs`, recorded in the file's
 * `generatedFromWebCommit`). Here we run the vendored copy under the identical
 * seed + fixture + config and assert deep equality.
 *
 * `provenance.test.ts` guarantees the web source behind those vectors is
 * unchanged; this test guarantees the vendored copy behaves identically.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';

import { planWeekAdvanced } from './mealPlanner.ts';
import { installSeededRandom } from './__fixtures__/prng.ts';
import { buildVectorConfig, type VectorConfigSpec } from './__fixtures__/vectorConfig.ts';

const DIR = import.meta.dirname;
const FIX = path.join(DIR, '__fixtures__');

type Row = Record<string, unknown>;
const fixtures: Record<string, Row[]> = {
  qa: JSON.parse(readFileSync(path.join(FIX, 'recipes.qa.json'), 'utf8')),
  pool: JSON.parse(readFileSync(path.join(FIX, 'recipes.pool.json'), 'utf8')),
};

interface Vector {
  name: string;
  fixture: keyof typeof fixtures;
  seed: number;
  config: VectorConfigSpec;
  lockedRecipeRefs: Record<string, number>;
  plan: Record<string, Row[]>;
}
interface VectorFile {
  generatedFromWebCommit: string;
  count: number;
  vectors: Vector[];
}

const vectorFile = JSON.parse(
  readFileSync(path.join(FIX, 'expected', 'vectors.json'), 'utf8'),
) as VectorFile;

test('vectors.json is present and non-trivial', () => {
  assert.match(vectorFile.generatedFromWebCommit, /^[0-9a-f]{40}$/);
  assert.ok(vectorFile.vectors.length >= 20, 'expected a broad vector matrix');
  assert.equal(vectorFile.vectors.length, vectorFile.count);
});

for (const vector of vectorFile.vectors) {
  test(`parity: ${vector.name}`, () => {
    const recipes = fixtures[vector.fixture];
    assert.ok(recipes, `unknown fixture ${vector.fixture}`);

    const config = buildVectorConfig(vector.config, recipes, vector.lockedRecipeRefs);

    const restore = installSeededRandom(vector.seed);
    let plan: Record<string, Row[]>;
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      plan = planWeekAdvanced(recipes as any, config as any);
    } finally {
      restore();
    }

    assert.deepStrictEqual(
      plan,
      vector.plan,
      `vendored planner diverged from the web canonical plan for "${vector.name}"`,
    );
  });
}

test('same seed + same input is deterministic across repeated runs', () => {
  const recipes = fixtures.pool;
  const spec = vectorFile.vectors.find((v) => v.fixture === 'pool')!;
  const config = buildVectorConfig(spec.config, recipes, spec.lockedRecipeRefs);

  const run = () => {
    const restore = installSeededRandom(spec.seed);
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      return planWeekAdvanced(recipes as any, config as any);
    } finally {
      restore();
    }
  };

  assert.deepStrictEqual(run(), run());
});
